(define (problem roverprob1234)
    (:domain rover)
    (:objects camera0 - camera colour - mode general - lander highres - mode lowres - mode objective0 - objective objective1 - objective rover0 - rover rover0store - store waypoint0 - waypoint waypoint1 - waypoint waypoint2 - waypoint waypoint3 - waypoint)
        (:init
(visiblefrom objective1 waypoint1)
(cantraverse rover0 waypoint2 waypoint1)
(onboard camera0 rover0)
(visible waypoint1 waypoint3)
(visiblefrom objective1 waypoint2)
(visiblefrom objective1 waypoint3)
(visiblefrom objective0 waypoint1)
(cantraverse rover0 waypoint3 waypoint0)
(cantraverse rover0 waypoint1 waypoint3)
(atlander general waypoint0)
(atsoilsample waypoint3)
(supports camera0 highres)
(visible waypoint3 waypoint0)
(equippedforimaging rover0)
(cantraverse rover0 waypoint1 waypoint2)
(visible waypoint1 waypoint0)
(atrocksample waypoint2)
(cantraverse rover0 waypoint0 waypoint3)
(visible waypoint2 waypoint0)
(channelfree general)
(atsoilsample waypoint0)
(empty rover0store)
(storeof rover0store rover0)
(visible waypoint1 waypoint2)
(visiblefrom objective1 waypoint0)
(equippedforrockanalysis rover0)
(atrocksample waypoint0)
(visible waypoint0 waypoint2)
(available rover0)
(visiblefrom objective0 waypoint0)
(visible waypoint2 waypoint1)
(visible waypoint0 waypoint1)
(visible waypoint3 waypoint1)
(atsoilsample waypoint2)
(calibrationtarget camera0 objective0)
(atrocksample waypoint1)
(visible waypoint2 waypoint3)
(visible waypoint3 waypoint2)
(equippedforsoilanalysis rover0)
(cantraverse rover0 waypoint3 waypoint1)
(supports camera0 colour)
(visiblefrom objective0 waypoint2)
(at rover0 waypoint3)
(visible waypoint0 waypoint3)
(visiblefrom objective0 waypoint3)
)
(:goal
    (and
		(communicatedrockdata waypoint0)
(communicatedimagedata objective0 colour)
(communicatedsoildata waypoint0)
)))